apiVersion: apps/v1
kind: Deployment
metadata:
  name: users
  labels:
    app: users
spec:
  replicas: {{ .Values.users.replicas }}
  selector:
    matchLabels:
      app: users
  template:
    metadata:
      labels:
        app: users
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 1000
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: users
          image: "{{ .Values.users.image }}:{{ .Values.users.tag }}"
          ports:
            - containerPort: 3001
          securityContext:
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsUser: 1000
            capabilities:
              drop:
                - ALL
            seccompProfile:
              type: RuntimeDefault
          readinessProbe:
            httpGet:
              path: /health
              port: 3001
            initialDelaySeconds: {{ .Values.users.readiness.initialDelaySeconds }}
            periodSeconds: {{ .Values.users.readiness.periodSeconds }}
          livenessProbe:
            httpGet:
              path: /health
              port: 3001
            initialDelaySeconds: {{ .Values.users.liveness.initialDelaySeconds }}
            periodSeconds: {{ .Values.users.liveness.periodSeconds }}
          resources:
{{ toYaml .Values.users.resources | indent 12 }}
---
apiVersion: v1
kind: Service
metadata:
  name: users
spec:
  selector:
    app: users
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3001
  type: ClusterIP
