name: CI

on:
  push:
    branches: ["main"]
    tags: "[0-9]*.[0-9]*.[0-9]*"
    paths:
      - "services/**/*"
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout      
      uses: actions/checkout@v4

    # Login to Docker Hub
    # https://github.com/docker/login-action
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    # Build and push users-service image
    - name: Build and push users-service image
      run: |
        docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/users-service:0.1.0 ./services/users-service
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/users-service:0.1.0

    # Build and push orders-service image
    - name: Build and push orders-service image
      run: |
        docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/orders-service:0.1.0 ./services/orders-service
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/orders-service:0.1.0

    # Build and push api-gateway image
    - name: Build and push api-gateway image
      run: |
        docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/api-service:0.1.0 ./services/api-gateway
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/api-service:0.1.0
